=== RevealBi/Reveal.Sdk.Dom/src/Reveal.Sdk.Dom.Tests/Schemas/RdashDocument.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "rdash-document.schema.json",
  "title": "Dashboard",
  "type": "object",
  "additionalProperties" : false,
  "properties": {
    "Title": {
      "required": true,
      "type": "string"
    },
    "Description": {
      "type": "string"
    },
    "ThemeName": {
      "required": true,
      "type": "string"
    },
    "CreatedWith": {
      "required": true,
      "type": "string"
    },
    "SavedWith": {
      "required": true,
      "type": "string"
    },
    "FormatVersion": {
      "required": true,
      "type": "integer"
    },
    "UseAutoLayout": {
      "required": true,
      "type": "boolean"
    },
    "Tags": {
      "type": "string"
    },
    "DataSources": {
      "required": true,
      "type": "array",
      "items": {
        "type": "any"
      }
    },
    "GlobalFilters": {
      "required": true,
      "type": "array",
      "items": {
        "type": "any"
      }
    },
    "GlobalVariables": {
      "required": true,
      "type": "array",
      "items": {
        "type": "any"
      }
    },
    "Widgets": {
      "required": true,
      "type": "array",
      "items": {
        "type": "any"
      }
    }
  }
}

=== RevealBi/Reveal.Sdk.Dom/Sandbox/Dashboards/Healthcare .json
{
  "Title": "Healthcare",
  "ThemeName": "Circus",
  "CreatedWith": "Web 1.0.369.0",
  "SavedWith": "Web 1.0.400.0",
  "FormatVersion": 6,
  "UseAutoLayout": false,
  "Tags": "u_e1df1c4e-2a5e-41ea-90ec-eb9d31711192",
  "Widgets": [
    {
      "Id": "d3b96d65-4251-40bb-8310-47595331f003",
      "RowSpan": 14,
      "ColumnSpan": 15,
      "IsTitleVisible": true,
      "Title": "Number of Inpatients",
      "DataSpec": {
        "_type": "TabularDataSpecType",
        "DataSourceItem": {
          "_type": "DataSourceItemType",
          "Id": "f678350c-92b5-4fd4-b300-54b95ee2b1a5__2535__https://infragisticsinc297.sharepoint.com/Groups/marketing/_api/Web/GetFileByServerRelativePath(decodedurl='/Groups/marketing/Products/Reveal/Samples.xlsx')/Healthcare",
          "Title": "Healthcare",
          "DataSourceId": "__EXCEL",
          "HasTabularData": true,
          "HasAsset": false,
          "Properties": {
            "Sheet": "Healthcare"
          },
          "Parameters": {},
          "ResourceItem": {
            "_type": "DataSourceItemType",
            "Id": "http://dl.infragistics.com/reportplus/reveal/samples/Samples.xlsx",
            "Title": "Samples.xlsx",
            "DataSourceId": "61ce395d-7a2e-4838-9f40-06e122505ad5",
            "HasTabularData": false,
            "HasAsset": true,
            "Properties": {
              "Url": "http://dl.infragistics.com/reportplus/reveal/samples/Samples.xlsx"
            },
            "Parameters": {}
          }
        },
        "Expiration": 1000,
        "Bindings": {
          "Bindings": []
        },
        "IsTransposed": false,
        "Fields": [
          {
            "FieldName": "Date",
            "FieldType": "Date",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Number of Inpatients",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Number of Outpatients",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Treatment Costs ",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "ER Wait Time",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Divison",
            "FieldType": "String",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Satisfaction ",
            "FieldType": "String",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Length of Stay ",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Charges per MD",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Current Paitents",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          }
        ],
        "TransposedFields": [],
        "QuickFilters": [],
        "AdditionalTables": [],
        "ServiceAdditionalTables": []
      },
      "VisualizationSettings": {
        "_type": "IndicatorVisualizationSettingsType",
        "VisualizationType": "INDICATOR",
        "DifferenceMode": "Percentage",
        "PositiveIsRed": false,
        "IncludeToday": true
      },
      "VisualizationDataSpec": {
        "_type": "IndicatorVisualizationDataSpecType",
        "AdHocExpandedElements": [],
        "Rows": [],
        "Date": {
          "_type": "DimensionColumnSpecType",
          "SummarizationField": {
            "_type": "SummarizationDateFieldType",
            "FieldName": "Date",
            "DrillDownElements": [],
            "ExpandedItems": [],
            "DateAggregationType": "Year"
          }
        },
        "Value": [
          {
            "_type": "MeasureColumnSpecType",
            "SummarizationField": {
              "_type": "SummarizationValueFieldType",
              "FieldName": "Number of Inpatients",
              "FieldLabel": "Number of Inpatients",
              "IsHidden": false,
              "AggregationType": "Sum",
              "Sorting": "None",
              "IsCalculated": false
            }
          }
        ],
        "IndicatorType": "YearToDatePreviousYear"
      },
      "PostTransformations": []
    },
    {
      "Id": "ba138823-feb4-4811-8b44-386372a26705",
      "RowSpan": 14,
      "ColumnSpan": 15,
      "IsTitleVisible": true,
      "Title": "Number of Outpatients",
      "DataSpec": {
        "_type": "TabularDataSpecType",
        "DataSourceItem": {
          "_type": "DataSourceItemType",
          "Id": "f678350c-92b5-4fd4-b300-54b95ee2b1a5__2535__https://infragisticsinc297.sharepoint.com/Groups/marketing/_api/Web/GetFileByServerRelativePath(decodedurl='/Groups/marketing/Products/Reveal/Samples.xlsx')/Healthcare",
          "Title": "Healthcare",
          "DataSourceId": "__EXCEL",
          "HasTabularData": true,
          "HasAsset": false,
          "Properties": {
            "Sheet": "Healthcare"
          },
          "Parameters": {},
          "ResourceItem": {
            "_type": "DataSourceItemType",
            "Id": "http://dl.infragistics.com/reportplus/reveal/samples/Samples.xlsx",
            "Title": "Samples.xlsx",
            "DataSourceId": "61ce395d-7a2e-4838-9f40-06e122505ad5",
            "HasTabularData": false,
            "HasAsset": true,
            "Properties": {
              "Url": "http://dl.infragistics.com/reportplus/reveal/samples/Samples.xlsx"
            },
            "Parameters": {}
          }
        },
        "Expiration": 1000,
        "Bindings": {
          "Bindings": []
        },
        "IsTransposed": false,
        "Fields": [
          {
            "FieldName": "Date",
            "FieldType": "Date",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Number of Inpatients",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Number of Outpatients",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Treatment Costs ",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "ER Wait Time",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Divison",
            "FieldType": "String",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Satisfaction ",
            "FieldType": "String",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Length of Stay ",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Charges per MD",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          },
          {
            "FieldName": "Current Paitents",
            "FieldType": "Number",
            "IsHidden": true,
            "IsCalculated": false,
            "Sorting": "None"
          }
        ],
        "TransposedFields": [],
        "QuickFilters": [],
        "AdditionalTables": [],
        "ServiceAdditionalTables": []
      },
      "VisualizationSettings": {
        "_type": "IndicatorVisualizationSettingsType",
        "VisualizationType": "INDICATOR",
        "DifferenceMode": "Percentage",
        "PositiveIsRed": false,
        "IncludeToday": true
      },
      "VisualizationDataSpec": {
        "_type": "IndicatorVisualizationDataSpecType",
        "AdHocExpandedElements": [],
        "Rows": [],
        "Date": {
          "_type": "DimensionColumnSpecType",
          "SummarizationField": {
            "_type": "SummarizationDateFieldType",
            "FieldName": "Date",
            "DrillDownElements": [],
            "ExpandedItems": [],
            "DateAggregationType": "Year"
          }
        },
        "Value": [
          {
            "_type": "MeasureColumnSpecType",
            "SummarizationField": {
              "_type": "SummarizationValueFieldType",
              "FieldName": "Number of Outpatients",
              "FieldLabel": "Number of Outpatients",
              "IsHidden": false,
              "AggregationType": "Sum",
              "Sorting": "None",
              "IsCalculated": false
            }
          }
        ],
        "IndicatorType": "YearToDatePreviousYear"
      },
      "PostTransformations": []
    },
    {
      "Id": "c8459802-fa6b-489a-c35d-63b1e316e2cf",
      "RowSpan": 14,
      "ColumnSpan": 15,
      "IsTitleVisible": true,
      "Title": "Average ER Wait Time (Min)",
